###
POST localhost:8080/2/inquire
Content-Type: application/x-www-form-urlencoded

question=Do you have any neurotic dogs?

###

POST localhost:8080/2/inquire
Content-Type: application/x-www-form-urlencoded

question=fantastic. how soon can i schedule an appointment to adopt Prancer?
